// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrU3HO6rLkpp2e8miG3MUkklVfH0y1GU',
    appId: '1:524600567382:web:448bc11ef6b98106d33df7',
    messagingSenderId: '524600567382',
    projectId: 'smart-park-13acd',
    authDomain: 'smart-park-13acd.firebaseapp.com',
    databaseURL: 'https://smart-park-13acd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-park-13acd.appspot.com',
    measurementId: 'G-TVB91EHSG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU9iIht__798rP5WlGwflvPKFCFN74ADY',
    appId: '1:524600567382:android:39bb94f583091a87d33df7',
    messagingSenderId: '524600567382',
    projectId: 'smart-park-13acd',
    databaseURL: 'https://smart-park-13acd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-park-13acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6JJuRQPlDPiG-0UeaOIQpZLjPFn3kRWs',
    appId: '1:524600567382:ios:b25c35f11a384933d33df7',
    messagingSenderId: '524600567382',
    projectId: 'smart-park-13acd',
    databaseURL: 'https://smart-park-13acd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-park-13acd.appspot.com',
    iosClientId: '524600567382-it6sqgosg65m81dh5m1d50al5rrcem4v.apps.googleusercontent.com',
    iosBundleId: 'none',
  );
}
