[sg.Radio('Car', 'TYPE', default=True, key='lot_type'),
    #     sg.Radio('Scooter', 'TYPE',key='lot_type')],
    #     [sg.Text('Parking Lot Name:'),
    #     sg.Input(key='lot_name')], [sg.Text('In order to create a parking lot, perform the following steps:')],
    #     # [sg.Text('1. Place a sample image of the parking lot in the \"Samples\" folder.\n2. Take a sample of one of the parking spaces.\n3. Outline the parking lot by clicking the top left of each lot.\n\t -Left click to add\n\t -Right click to remove\n4. Press \"s\" to save, \"q\" to quit.')],
    #     [sg.Text('Select the sample image of the parking lot')],
    #     [sg.Input(key='image_path'), sg.FileBrowse()],